### PR TITLE
[FEATURE] Enhance `slot.render` view-helper

### PR DESCRIPTION
**Pull request by romm**
This view-helper can now use two new features, for a total of three ways
to render a slot.

Inline
------

The processed slot value will be returned.

```html
<nz:slot.render name="MySlot"
                markers="{foo: 'bar'}" />
```

Conditional
-----------

Can be used to check whether the slot exists, and do something if it
doesn't. When using this way, a variable `slotValue` becomes accessible
within the view-helper, that contains the processed value of the slot.
However, this variable is filled only when the slot exists and can be
processed.

```html
<nz:slot.render name="SomeOptionalSlot">
    <f:then>
        {slotValue -> f:format.html()}
    </f:then>
    <f:else>
        Some default value
    </f:else>
</nz:slot.render>
```

Wrapping
--------

You may need to add HTML around the slot value only when the slot
exists.

```html
<nz:slot.render name="SomeOptionalSlot">
    <hr />
    <div class="some-class">
        {slotValue}
    </div>
</nz:slot.render>
```

### CODE REVIEW

**Comment by Mopolo** [comment]
Why no use the inside of the `<nz:slot.render>` ViewHelper as the default content instead?

**Review by Mopolo — CHANGES_REQUESTED** [review]
Why no use the inside of the `<nz:slot.render>` ViewHelper as the default content instead?

**Comment by romm** [comment]
@Mopolo good idea. Drastic changes have been made. Could you please add a functional review on this one? Check at least on TYPO3 v8 and v7 if you can.

**Comment by Mopolo** [comment]
I tested it on TYPO3 `7.6.21` with this code and it works:

```html
<f:section name="Slots">
    <nz:slot.text name="RealSlot" label="Slot foo" />
</f:section>

<f:section name="Body">
    <f:format.html>
        <div>
            <h1>RealSlot with markers, short</h1>
            <nz:slot.render name="RealSlot" markers="{user: 'john'}"/>
        </div>

        <div>
            <h1>RealSlot without markers, short</h1>
            <nz:slot.render name="RealSlot"/>
        </div>

        <div>
            <h1>RealSlot with markers, inside tag</h1>
            <nz:slot.render name="RealSlot" markers="{user: 'john'}">
                {slotValue}
            </nz:slot.render>
        </div>

        <div>
            <h1>RealSlot without markers, inside tag</h1>
            <nz:slot.render name="RealSlot">
                {slotValue}
            </nz:slot.render>
        </div>

        <div>
            <h1>RealSlot with markers, with wrapping</h1>
            <nz:slot.render name="RealSlot" markers="{user: 'john'}">
                <hr/>
                {slotValue}
                <hr/>
            </nz:slot.render>
        </div>

        <div>
            <h1>RealSlot with markers, with only f:then</h1>
            <nz:slot.render name="RealSlot" markers="{user: 'john'}">
                <f:then>
                    {slotValue}
                </f:then>
            </nz:slot.render>
        </div>

        <div>
            <h1>RealSlot with markers, with only f:else</h1>
            <nz:slot.render name="RealSlot" markers="{user: 'john'}">
                <f:else>
                    {slotValue}
                </f:else>
            </nz:slot.render>
        </div>

        <div>
            <h1>FakeSlot full</h1>
            <nz:slot.render name="FakeSlot">
                <f:then>
                    Slot exists
                </f:then>
                <f:else>
                    Slot does not exists
                </f:else>
            </nz:slot.render>
        </div>

        <div>
            <h1>FakeSlot with only f:then</h1>
            <nz:slot.render name="FakeSlot">
                <f:then>
                    Slot exists
                </f:then>
            </nz:slot.render>
        </div>

        <div>
            <h1>FakeSlot with only f:else</h1>
            <nz:slot.render name="FakeSlot">
                <f:else>
                    Slot does not exists
                </f:else>
            </nz:slot.render>
        </div>

        <div>
            <h1>FakeSlot with content</h1>
            <nz:slot.render name="FakeSlot">
                Slot exists
            </nz:slot.render>
        </div>

        <div>
            <h1>FakeSlot short</h1>
            <nz:slot.render name="FakeSlot"/>
        </div>
    </f:format.html>
</f:section>
```

**Comment by romm** [comment]
Perfect. I tried on v8 with the same code; seems to work as well. 👍

**Review by Mopolo — APPROVED** [review]

**Pull request merged**
