### PR TITLE
[BUGFIX] Issue #170 {email} property accepts now multiple email addre…

### PR DESCRIPTION
**Pull request by ogrosko**
Issue #170 bugfix
`{email}` property now accept multiple email addresses

### CODE REVIEW

**Comment by romm** [comment]
Tested, works like a charm. Thank you for your work!

Two things though:

- Could you add the `.idea` in `.gitignore ` in a separated PR? This is another context and we want the Git historic as clean as possible.
- I think this would be interesting to add some documentation concerning multiple addresses in an email property. Do you think you could manage it? 😄

**Comment by ogrosko** [comment]
@romm check it ;)

**Review by romm — APPROVED** [review]

**Comment by romm** [comment]
Damn, I pressed `Enter` key instead of `Erase`, the commit name is completely wrong!

**Comment by romm** [comment]
Ok, I fixed it. Thank you for your first contribution!

**Pull request merged**
